version: '3.8'

services:
  # MinIO Object Storage for file storage
  minio:
    image: minio/minio:latest
    container_name: cw-agent-minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - cw-agent-network
      
  # Set up MinIO bucket
  createbuckets:
    image: minio/mc
    container_name: cw-agent-createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing myminio/chat-attachments;
      /usr/bin/mc anonymous set download myminio/chat-attachments;
      exit 0;
      "
    networks:
      - cw-agent-network
    
volumes:
  minio_data:
    name: cw-agent-minio-data
    
networks:
  cw-agent-network:
    name: cw-agent-network 