import { NextRequest, NextResponse } from 'next/server';
import * as memoryManager from '../../../server/qdrant';

/**
 * API endpoint to update tags for a memory entry
 * Supports approving suggested tags or rejecting them
 */
export async function POST(req: NextRequest) {
  try {
    const { memoryId, tags, action } = await req.json();
    
    // Validate required fields
    if (!memoryId) {
      return NextResponse.json({ success: false, error: 'Memory ID is required' }, { status: 400 });
    }
    
    if (action === 'approve') {
      // Validate tags array
      if (!Array.isArray(tags)) {
        return NextResponse.json({ success: false, error: 'Tags must be an array' }, { status: 400 });
      }
      
      // Update tags with approved status
      const success = await memoryManager.updateMemoryTags(memoryId, tags, true);
      
      if (success) {
        return NextResponse.json({ 
          success: true, 
          message: 'Tags approved successfully',
          memoryId,
          tags
        });
      } else {
        return NextResponse.json({ 
          success: false, 
          error: 'Failed to update tags'
        }, { status: 500 });
      }
    } else if (action === 'reject') {
      // Clear suggested tags
      const success = await memoryManager.updateMemoryMetadata(memoryId, {
        tagsRejected: true,
        autoGeneratedTags: false,
        suggestedTags: null
      });
      
      if (success) {
        return NextResponse.json({ 
          success: true, 
          message: 'Tag suggestions rejected successfully',
          memoryId
        });
      } else {
        return NextResponse.json({ 
          success: false, 
          error: 'Failed to reject tag suggestions'
        }, { status: 500 });
      }
    } else {
      return NextResponse.json({ 
        success: false, 
        error: 'Invalid action. Must be "approve" or "reject"'
      }, { status: 400 });
    }
  } catch (error) {
    console.error('Error updating memory tags:', error);
    return NextResponse.json({ 
      success: false, 
      error: 'Failed to process request'
    }, { status: 500 });
  }
} 